### ISSUE TITLE
README.md 파일중 누락부분이 있습니다.

### ISSUE THREAD

**Issue by songheony** [deep-diver/Machine-Learning-Yearning-Korean-Translation#1]
18 "눈알"과 "블랙박스" 개발데이터셋은 얼마나 커야 할까?
의 부분의 링크가 걸려있지 않습니다.
18_How_big_should_the_Eyeball_and_Blackbox_dev_sets_be.md 와 링크 시킬 필요가 있을것 같습니다.

**Comment by deep-diver** [comment]
응대가 늦었네요 ㅠ

수정 하였습니다. 감사합니다 ^^
